
import { ProjectState } from '../types';

export const DEMO_PROJECT_DATA: Omit<ProjectState, 'history'> = {
  "patterns": [
    {
      "id": "pat-ai-0-2veym",
      "name": "INTRO",
      "channels": {
        "1": [
          { "id": "p0-c1-0", "step": 0, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-2", "step": 2, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-4", "step": 4, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-6", "step": 6, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-8", "step": 8, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-10", "step": 10, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-12", "step": 12, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-14", "step": 14, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-16", "step": 16, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-18", "step": 18, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-20", "step": 20, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-22", "step": 22, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-24", "step": 24, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-26", "step": 26, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-28", "step": 28, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-30", "step": 30, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-32", "step": 32, "pitch": "F#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-34", "step": 34, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-36", "step": 36, "pitch": "F#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-38", "step": 38, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-40", "step": 40, "pitch": "F#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-42", "step": 42, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-44", "step": 44, "pitch": "F#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-46", "step": 46, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-48", "step": 48, "pitch": "G#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-50", "step": 50, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-52", "step": 52, "pitch": "G#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-54", "step": 54, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-56", "step": 56, "pitch": "G#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-58", "step": 58, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c1-60", "step": 60, "pitch": "G#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p0-c1-62", "step": 62, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" }
        ],
        "2": [
          { "id": "p0-c2-0", "step": 0, "pitch": "D#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-2", "step": 2, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-8", "step": 8, "pitch": "D#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-10", "step": 10, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-16", "step": 16, "pitch": "D#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-18", "step": 18, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-24", "step": 24, "pitch": "D#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-26", "step": 26, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-32", "step": 32, "pitch": "F#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-34", "step": 34, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-40", "step": 40, "pitch": "F#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-42", "step": 42, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-48", "step": 48, "pitch": "G#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-50", "step": 50, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c2-56", "step": 56, "pitch": "G#4", "instrument": "LEAD", "volume": 8, "dutyCycle": "0.5" },
          { "id": "p0-c2-58", "step": 58, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" }
        ],
        "3": [
          { "id": "p0-c3-0", "step": 0, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-2", "step": 2, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-4", "step": 4, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-6", "step": 6, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-8", "step": 8, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-10", "step": 10, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-12", "step": 12, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-14", "step": 14, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-16", "step": 16, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-18", "step": 18, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-20", "step": 20, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-22", "step": 22, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-24", "step": 24, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-26", "step": 26, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-28", "step": 28, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-30", "step": 30, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-32", "step": 32, "pitch": "F#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-34", "step": 34, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-36", "step": 36, "pitch": "F#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-38", "step": 38, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-40", "step": 40, "pitch": "F#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-42", "step": 42, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-44", "step": 44, "pitch": "F#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-46", "step": 46, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-48", "step": 48, "pitch": "G#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-50", "step": 50, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-52", "step": 52, "pitch": "G#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-54", "step": 54, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-56", "step": 56, "pitch": "G#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-58", "step": 58, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p0-c3-60", "step": 60, "pitch": "G#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p0-c3-62", "step": 62, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" }
        ],
        "4": [
          { "id": "p0-c4-0", "step": 0, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-1", "step": 1, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-4", "step": 4, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-5", "step": 5, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-8", "step": 8, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-9", "step": 9, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-12", "step": 12, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-13", "step": 13, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-16", "step": 16, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-17", "step": 17, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-20", "step": 20, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-21", "step": 21, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-24", "step": 24, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-25", "step": 25, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-28", "step": 28, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-29", "step": 29, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-32", "step": 32, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-33", "step": 33, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-36", "step": 36, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-37", "step": 37, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-40", "step": 40, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-41", "step": 41, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-44", "step": 44, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-45", "step": 45, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-48", "step": 48, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-49", "step": 49, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-52", "step": 52, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-53", "step": 53, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-56", "step": 56, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p0-c4-57", "step": 57, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p0-c4-60", "step": 60, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-61", "step": 61, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-62", "step": 62, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p0-c4-63", "step": 63, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 }
        ]
      }
    },
    {
      "id": "pat-ai-1-4xrd5",
      "name": "VERSE",
      "channels": {
        "1": [
          { "id": "p1-c1-0", "step": 0, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-2", "step": 2, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-3", "step": 3, "pitch": "C#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-5", "step": 5, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-6", "step": 6, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-8", "step": 8, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-16", "step": 16, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-18", "step": 18, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-19", "step": 19, "pitch": "F#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-21", "step": 21, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-22", "step": 22, "pitch": "D#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-24", "step": 24, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-32", "step": 32, "pitch": "B-4", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-34", "step": 34, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-35", "step": 35, "pitch": "A#4", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-37", "step": 37, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-38", "step": 38, "pitch": "B-4", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-40", "step": 40, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-48", "step": 48, "pitch": "A#4", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-50", "step": 50, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-51", "step": 51, "pitch": "G#4", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-53", "step": 53, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c1-56", "step": 56, "pitch": "A#4", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.125" },
          { "id": "p1-c1-58", "step": 58, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" }
        ],
        "2": [
          { "id": "p1-c2-0", "step": 0, "pitch": "D#4", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p1-c2-2", "step": 2, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-8", "step": 8, "pitch": "D#4", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p1-c2-10", "step": 10, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-16", "step": 16, "pitch": "D#4", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p1-c2-18", "step": 18, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-24", "step": 24, "pitch": "D#4", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p1-c2-26", "step": 26, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-32", "step": 32, "pitch": "B-3", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p1-c2-34", "step": 34, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-40", "step": 40, "pitch": "B-3", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p1-c2-42", "step": 42, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-48", "step": 48, "pitch": "A#3", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p1-c2-50", "step": 50, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c2-56", "step": 56, "pitch": "A#3", "instrument": "LEAD", "volume": 7, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p1-c2-58", "step": 58, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" }
        ],
        "3": [
          { "id": "p1-c3-0", "step": 0, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-1", "step": 1, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-2", "step": 2, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-3", "step": 3, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-4", "step": 4, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-5", "step": 5, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-6", "step": 6, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-7", "step": 7, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-16", "step": 16, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-17", "step": 17, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-18", "step": 18, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-19", "step": 19, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-20", "step": 20, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-21", "step": 21, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-22", "step": 22, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-23", "step": 23, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-32", "step": 32, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-33", "step": 33, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-34", "step": 34, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-35", "step": 35, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-36", "step": 36, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-37", "step": 37, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-38", "step": 38, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-39", "step": 39, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-48", "step": 48, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-49", "step": 49, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-50", "step": 50, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-51", "step": 51, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-52", "step": 52, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-53", "step": 53, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p1-c3-54", "step": 54, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p1-c3-55", "step": 55, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" }
        ],
        "4": [
          { "id": "p1-c4-0", "step": 0, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p1-c4-1", "step": 1, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-2", "step": 2, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-3", "step": 3, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-4", "step": 4, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p1-c4-5", "step": 5, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-6", "step": 6, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-7", "step": 7, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-16", "step": 16, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p1-c4-17", "step": 17, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-18", "step": 18, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-19", "step": 19, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-20", "step": 20, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p1-c4-21", "step": 21, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-22", "step": 22, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-23", "step": 23, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-32", "step": 32, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p1-c4-33", "step": 33, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-34", "step": 34, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-35", "step": 35, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-36", "step": 36, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p1-c4-37", "step": 37, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-38", "step": 38, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-39", "step": 39, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-48", "step": 48, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p1-c4-49", "step": 49, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-50", "step": 50, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-51", "step": 51, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-52", "step": 52, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p1-c4-53", "step": 53, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-54", "step": 54, "pitch": "C-6", "instrument": "HAT", "volume": 8, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p1-c4-55", "step": 55, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-56", "step": 56, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p1-c4-57", "step": 57, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p1-c4-60", "step": 60, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p1-c4-61", "step": 61, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" }
        ]
      }
    },
    {
      "id": "pat-ai-2-n4q95",
      "name": "CHORUS",
      "channels": {
        "1": [
          { "id": "p2-c1-0", "step": 0, "pitch": "D#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25", "effect": "VIBRATO" },
          { "id": "p2-c1-4", "step": 4, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-8", "step": 8, "pitch": "G#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-10", "step": 10, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-12", "step": 12, "pitch": "A#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-14", "step": 14, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-16", "step": 16, "pitch": "B-5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25", "effect": "VIBRATO" },
          { "id": "p2-c1-20", "step": 20, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-24", "step": 24, "pitch": "G#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-26", "step": 26, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-28", "step": 28, "pitch": "F#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-30", "step": 30, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-32", "step": 32, "pitch": "G#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25", "effect": "VIBRATO" },
          { "id": "p2-c1-36", "step": 36, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-40", "step": 40, "pitch": "G#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-42", "step": 42, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-44", "step": 44, "pitch": "B-5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-46", "step": 46, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c1-48", "step": 48, "pitch": "A#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25", "effect": "VIBRATO" },
          { "id": "p2-c1-52", "step": 52, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c1-60", "step": 60, "pitch": "C#6", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.25" },
          { "id": "p2-c1-62", "step": 62, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" }
        ],
        "2": [
          { "id": "p2-c2-0", "step": 0, "pitch": "D#4", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-2", "step": 2, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-4", "step": 4, "pitch": "D#4", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-6", "step": 6, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-8", "step": 8, "pitch": "D#4", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-10", "step": 10, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-12", "step": 12, "pitch": "D#4", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-14", "step": 14, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-16", "step": 16, "pitch": "B-3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p2-c2-18", "step": 18, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-20", "step": 20, "pitch": "B-3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p2-c2-22", "step": 22, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-24", "step": 24, "pitch": "B-3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p2-c2-26", "step": 26, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-28", "step": 28, "pitch": "B-3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p2-c2-30", "step": 30, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-32", "step": 32, "pitch": "G#3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-34", "step": 34, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-36", "step": 36, "pitch": "G#3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-38", "step": 38, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-40", "step": 40, "pitch": "G#3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-42", "step": 42, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-44", "step": 44, "pitch": "G#3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,3,7" },
          { "id": "p2-c2-46", "step": 46, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-48", "step": 48, "pitch": "A#3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p2-c2-50", "step": 50, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c2-56", "step": 56, "pitch": "A#3", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.25", "effect": "ARPEGGIO", "arpNotes": "0,4,7" },
          { "id": "p2-c2-58", "step": 58, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" }
        ],
        "3": [
          { "id": "p2-c3-0", "step": 0, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-1", "step": 1, "pitch": "OFF", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p2-c3-2", "step": 2, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-4", "step": 4, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-6", "step": 6, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-8", "step": 8, "pitch": "D#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-10", "step": 10, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-12", "step": 12, "pitch": "C#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-14", "step": 14, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-16", "step": 16, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-18", "step": 18, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-20", "step": 20, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-22", "step": 22, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-24", "step": 24, "pitch": "B-1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-26", "step": 26, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-28", "step": 28, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-30", "step": 30, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-32", "step": 32, "pitch": "G#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-34", "step": 34, "pitch": "G#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-36", "step": 36, "pitch": "G#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-38", "step": 38, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-40", "step": 40, "pitch": "G#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-42", "step": 42, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-44", "step": 44, "pitch": "F#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-46", "step": 46, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-48", "step": 48, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-50", "step": 50, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-56", "step": 56, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-58", "step": 58, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c3-60", "step": 60, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p2-c3-62", "step": 62, "pitch": "A#1", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" }
        ],
        "4": [
          { "id": "p2-c4-0", "step": 0, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-1", "step": 1, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-2", "step": 2, "pitch": "C-6", "instrument": "HAT", "volume": 10, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p2-c4-3", "step": 3, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-4", "step": 4, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-5", "step": 5, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-6", "step": 6, "pitch": "C-6", "instrument": "HAT", "volume": 10, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p2-c4-7", "step": 7, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-8", "step": 8, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-9", "step": 9, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-10", "step": 10, "pitch": "C-6", "instrument": "HAT", "volume": 10, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p2-c4-11", "step": 11, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-12", "step": 12, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-13", "step": 13, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-14", "step": 14, "pitch": "C-6", "instrument": "HAT", "volume": 10, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p2-c4-15", "step": 15, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-16", "step": 16, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-17", "step": 17, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-20", "step": 20, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-21", "step": 21, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-24", "step": 24, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-25", "step": 25, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-28", "step": 28, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-29", "step": 29, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-32", "step": 32, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-33", "step": 33, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-36", "step": 36, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-37", "step": 37, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-40", "step": 40, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-41", "step": 41, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-44", "step": 44, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-45", "step": 45, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-48", "step": 48, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-49", "step": 49, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-52", "step": 52, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-53", "step": 53, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-56", "step": 56, "pitch": "C-2", "instrument": "KICK", "volume": 15, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p2-c4-57", "step": 57, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p2-c4-60", "step": 60, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-61", "step": 61, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-62", "step": 62, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p2-c4-63", "step": 63, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 }
        ]
      }
    },
    {
      "id": "pat-ai-3-9pgdi",
      "name": "BRIDGE",
      "channels": {
        "1": [
          { "id": "p3-c1-0", "step": 0, "pitch": "B-4", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.5" },
          { "id": "p3-c1-4", "step": 4, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c1-8", "step": 8, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c1-16", "step": 16, "pitch": "C#5", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.5" },
          { "id": "p3-c1-20", "step": 20, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c1-24", "step": 24, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c1-32", "step": 32, "pitch": "D#5", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.5" },
          { "id": "p3-c1-36", "step": 36, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c1-40", "step": 40, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c1-48", "step": 48, "pitch": "F-5", "instrument": "LEAD", "volume": 10, "dutyCycle": "0.5" },
          { "id": "p3-c1-52", "step": 52, "pitch": "F#5", "instrument": "LEAD", "volume": 11, "dutyCycle": "0.5" },
          { "id": "p3-c1-56", "step": 56, "pitch": "G#5", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c1-60", "step": 60, "pitch": "A#5", "instrument": "LEAD", "volume": 15, "dutyCycle": "0.5" }
        ],
        "2": [
          { "id": "p3-c2-0", "step": 0, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.25" },
          { "id": "p3-c2-16", "step": 16, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.25" },
          { "id": "p3-c2-32", "step": 32, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.25" },
          { "id": "p3-c2-48", "step": 48, "pitch": "OFF", "instrument": "LEAD", "volume": 12, "dutyCycle": "0.25" }
        ],
        "3": [
          { "id": "p3-c3-0", "step": 0, "pitch": "B-1", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-2", "step": 2, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-4", "step": 4, "pitch": "B-1", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-6", "step": 6, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-8", "step": 8, "pitch": "B-1", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-10", "step": 10, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-12", "step": 12, "pitch": "B-1", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-14", "step": 14, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-16", "step": 16, "pitch": "C#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-18", "step": 18, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-20", "step": 20, "pitch": "C#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-22", "step": 22, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-24", "step": 24, "pitch": "C#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-26", "step": 26, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-28", "step": 28, "pitch": "C#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-30", "step": 30, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-32", "step": 32, "pitch": "D#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-34", "step": 34, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-36", "step": 36, "pitch": "D#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-38", "step": 38, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-40", "step": 40, "pitch": "D#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-42", "step": 42, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-44", "step": 44, "pitch": "D#2", "instrument": "SUB", "volume": 12, "dutyCycle": "0.5" },
          { "id": "p3-c3-46", "step": 46, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-48", "step": 48, "pitch": "F-2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p3-c3-50", "step": 50, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-52", "step": 52, "pitch": "F#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p3-c3-54", "step": 54, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-56", "step": 56, "pitch": "G#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p3-c3-58", "step": 58, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c3-60", "step": 60, "pitch": "A#2", "instrument": "SUB", "volume": 15, "dutyCycle": "0.5" },
          { "id": "p3-c3-62", "step": 62, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" }
        ],
        "4": [
          { "id": "p3-c4-0", "step": 0, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-1", "step": 1, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-4", "step": 4, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-5", "step": 5, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-8", "step": 8, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-9", "step": 9, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-12", "step": 12, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-13", "step": 13, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-16", "step": 16, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-17", "step": 17, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-20", "step": 20, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-21", "step": 21, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-24", "step": 24, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-25", "step": 25, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-28", "step": 28, "pitch": "C-6", "instrument": "HAT", "volume": 5, "dutyCycle": "0.125", "decay": 14 },
          { "id": "p3-c4-29", "step": 29, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-32", "step": 32, "pitch": "C-2", "instrument": "KICK", "volume": 10, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p3-c4-33", "step": 33, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-36", "step": 36, "pitch": "C-2", "instrument": "KICK", "volume": 10, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p3-c4-37", "step": 37, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-40", "step": 40, "pitch": "C-2", "instrument": "KICK", "volume": 10, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p3-c4-41", "step": 41, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-44", "step": 44, "pitch": "C-2", "instrument": "KICK", "volume": 10, "dutyCycle": "0.5", "decay": 12 },
          { "id": "p3-c4-45", "step": 45, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-48", "step": 48, "pitch": "C-5", "instrument": "SNARE", "volume": 8, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-49", "step": 49, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-50", "step": 50, "pitch": "C-5", "instrument": "SNARE", "volume": 9, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-51", "step": 51, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-52", "step": 52, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-53", "step": 53, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-54", "step": 54, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-55", "step": 55, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-56", "step": 56, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-57", "step": 57, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-58", "step": 58, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-59", "step": 59, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-60", "step": 60, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-61", "step": 61, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" },
          { "id": "p3-c4-62", "step": 62, "pitch": "C-5", "instrument": "SNARE", "volume": 10, "dutyCycle": "0.5", "decay": 8 },
          { "id": "p3-c4-63", "step": 63, "pitch": "OFF", "instrument": "---", "volume": 0, "dutyCycle": "0.5" }
        ]
      }
    }
  ],
  "arrangement": [
    "pat-ai-0-2veym",
    "pat-ai-1-4xrd5",
    "pat-ai-2-n4q95",
    "pat-ai-1-4xrd5",
    "pat-ai-2-n4q95",
    "pat-ai-3-9pgdi",
    "pat-ai-2-n4q95",
    "pat-ai-0-2veym",
    "pat-ai-2-n4q95"
  ],
  "bpm": 160,
  "activePatternId": "pat-ai-2-n4q95",
  "samples": [],
  "customClips": []
};
